
export let SimpleEntrances: string[] = [
    "Castle Town -> Castle Town Bazaar",
    "Castle Town -> Castle Town Bombchu Bowling",
    "Castle Town -> Castle Town Bombchu Shop",
    "Castle Town -> Castle Town Man in Green House",
    "Castle Town -> Castle Town Mask Shop",
    "Castle Town -> Castle Town Potion Shop",
    "Castle Town -> Castle Town Shooting Gallery",
    "Castle Town -> Castle Town Treasure Chest Game",
    "Castle Town Entrance -> Castle Town Rupee Room",
    "Death Mountain -> Mountain Storms Grotto",
    "Death Mountain Crater Lower Nearby -> Crater Fairy",
    "Death Mountain Crater Lower Nearby -> DMC Hammer Grotto",
    "Death Mountain Crater Upper Nearby -> Top of Crater Grotto",
    "Death Mountain Summit -> Mountain Bombable Grotto",
    "Death Mountain Summit -> Mountain Summit Fairy",
    "Desert Colossus -> Colossus Fairy",
    "Desert Colossus -> Desert Colossus Grotto",
    "Desert Colossus Grotto",
    "Ganons Castle Grounds -> Ganons Castle Fairy",
    "Gerudo Fortress -> Gerudo Fortress Storms Grotto",
    "Gerudo Valley -> Gerudo Valley Octorok Grotto",
    "Gerudo Valley Far Side -> Carpenter Tent",
    "Gerudo Valley Far Side -> Gerudo Valley Storms Grotto",
    "Goron City -> Goron City Grotto",
    "Goron City -> Goron Shop",
    "Graveyard -> Composer Grave",
    "Graveyard -> Dampes House",
    "Graveyard -> Heart Piece Grave",
    "Graveyard -> Shield Grave",
    "Hyrule Castle Grounds -> Castle Storms Grotto",
    "Hyrule Castle Grounds -> Hyrule Castle Fairy",
    "Hyrule Field -> Field Far West Castle Town Grotto",
    "Hyrule Field -> Field Kakariko Grotto",
    "Hyrule Field -> Field Near Lake Inside Fence Grotto",
    "Hyrule Field -> Field Near Lake Outside Fence Grotto",
    "Hyrule Field -> Field North Lon Lon Grotto",
    "Hyrule Field -> Field Valley Grotto",
    "Hyrule Field -> Field West Castle Town Grotto",
    "Hyrule Field -> Remote Southern Grotto",
    "Kakariko Impa Ledge -> Impas House Back",
    "Kakariko Village -> Carpenter Boss House",
    "Kakariko Village -> House of Skulltula",
    "Kakariko Village -> Impas House",
    "Kakariko Village -> Kakariko Bazaar",
    "Kakariko Village -> Kakariko Bombable Grotto",
    "Kakariko Village -> Kakariko Shooting Gallery",
    "Kakariko Village Backyard -> Kakariko Back Grotto",
    "Kakariko Village Backyard -> Odd Medicine Building",
    "Kokiri Forest -> House of Twins",
    "Kokiri Forest -> Know It All House",
    "Kokiri Forest -> Kokiri Forest Storms Grotto",
    "Kokiri Forest -> Kokiri Shop",
    "Kokiri Forest -> Mido House",
    "Kokiri Forest -> Saria House",
    "Lake Hylia -> Fishing Hole",
    "Lake Hylia -> Lake Hylia Grotto",
    "Lake Hylia -> Lake Hylia Lab",
    "Lon Lon Ranch -> Ingo Barn",
    "Lon Lon Ranch -> Lon Lon Corner Tower",
    "Lon Lon Ranch -> Lon Lon Grotto",
    "Lon Lon Ranch -> Talon House",
    "Lost Woods -> Lost Woods Generic Grotto",
    "Lost Woods Beyond Mido -> Deku Theater",
    "Lost Woods Beyond Mido -> Lost Woods Sales Grotto",
    "Sacred Forest Meadow -> Meadow Fairy Grotto",
    "Sacred Forest Meadow -> Meadow Storms Grotto",
    "Sacred Forest Meadow Entryway -> Front of Meadow Grotto",
    "Zora River -> Zora River Plateau Bombable Grotto",
    "Zora River -> Zora River Plateau Open Grotto",
    "Zora River -> Zora River Storms Grotto",
    "Zoras Domain -> Zora Shop",
    "Zoras Domain -> Zoras Domain Storms Grotto",
    "Zoras Fountain -> Zoras Fountain Fairy"
];
