import { LocationPool } from "../Types/LocationPool";

export let GoldSkulltulaOverworldLocationPool: LocationPool = [
    "GS Kokiri Know It All House",
    "GS Kokiri Bean Patch",
    "GS Kokiri House of Twins",
    "GS Lost Woods Bean Patch Near Bridge",
    "GS Lost Woods Above Stage",
    "GS Lost Woods Bean Patch Near Stage",
    "GS Sacred Forest Meadow",
    "GS Lake Hylia Bean Patch",
    "GS Lake Hylia Lab Wall",
    "GS Lake Hylia Small Island",
    "GS Lake Hylia Giant Tree",
    "GS Lab Underwater Crate",
    "GS Gerudo Valley Small Bridge",
    "GS Gerudo Valley Bean Patch",
    "GS Gerudo Valley Behind Tent",
    "GS Gerudo Valley Pillar",
    "GS Gerudo Fortress Archery Range",
    "GS Gerudo Fortress Top Floor",
    "GS Wasteland Ruins",
    "GS Desert Colossus Bean Patch",
    "GS Desert Colossus Tree",
    "GS Desert Colossus Hill",
    "GS Hyrule Castle Tree",
    "GS Outside Ganon's Castle",
    "GS Castle Market Guard House",
    "GS Kakariko House Under Construction",
    "GS Kakariko Skulltula House",
    "GS Kakariko Guard's House",
    "GS Kakariko Tree",
    "GS Kakariko Watchtower",
    "GS Kakariko Above Impa's House",
    "GS Graveyard Wall",
    "GS Graveyard Bean Patch",
    "GS Mountain Trail Bean Patch",
    "GS Mountain Trail Bomb Alcove",
    "GS Mountain Trail Above Dodongo's Cavern",
    "GS Mountain Trail Path to Crater",
    "GS Goron City Boulder Maze",
    "GS Goron City Center Platform",
    "GS Death Mountain Crater Crate",
    "GS Mountain Crater Bean Patch",
    "GS Zora River Tree",
    "GS Zora River Ladder",
    "GS Zora River Near Raised Grottos",
    "GS Zora River Above Bridge",
    "GS Zora's Domain Frozen Waterfall",
    "GS Zora's Fountain Tree",
    "GS Zora's Fountain Above the Log",
    "GS Zora's Fountain Hidden Cave",
    "GS Lon Lon Ranch Tree",
    "GS Lon Lon Ranch Rain Shed",
    "GS Lon Lon Ranch House Window",
    "GS Lon Lon Ranch Back Wall",
    "GS Hyrule Field Near Gerudo Valley",
    "GS Hyrule Field near Kakariko",
    "GS Hyrule Castle Grotto"
];
