import { LocationPoolType } from "../Types/LocationPoolType";

export let GoldSkulltulaDungeonLocationPool: LocationPoolType = [
    "GS Deku Tree Compass Room",
    "GS Deku Tree Basement Vines",
    "GS Deku Tree Basement Gate",
    "GS Deku Tree Basement Back Room",
    "GS Dodongo's Cavern East Side Room",
    "GS Dodongo's Cavern Scarecrow",
    "GS Dodongo's Cavern Vines Above Stairs",
    "GS Dodongo's Cavern Alcove Above Stairs",
    "GS Dodongo's Cavern Back Room",
    "GS Jabu Jabu Water Switch Room",
    "GS Jabu Jabu Lobby Basement Lower",
    "GS Jabu Jabu Lobby Basement Upper",
    "GS Jabu Jabu Near Boss",
    "GS Forest Temple First Room",
    "GS Forest Temple Lobby",
    "GS Forest Temple Outdoor West",
    "GS Forest Temple Outdoor East",
    "GS Forest Temple Basement",
    "GS Well West Inner Room",
    "GS Well East Inner Room",
    "GS Well Like Like Cage",
    "GS Fire Temple Basement",
    "GS Fire Temple Song of Time Room",
    "GS Fire Temple Unmarked Bomb Wall",
    "GS Fire Temple East Tower Climb",
    "GS Fire Temple East Tower Top",
    "GS Ice Cavern Spinning Scythe Room",
    "GS Ice Cavern Heart Piece Room",
    "GS Ice Cavern Push Block Room",
    "GS Water Temple South Basement",
    "GS Water Temple Near Boss Key Chest",
    "GS Water Temple Central Room",
    "GS Water Temple Serpent River",
    "GS Water Temple Falling Platform Room",
    "GS Shadow Temple Like Like Room",
    "GS Shadow Temple Crusher Room",
    "GS Shadow Temple Single Giant Pot",
    "GS Shadow Temple Near Ship",
    "GS Shadow Temple Triple Giant Pot",
    "GS Spirit Temple Metal Fence",
    "GS Spirit Temple Bomb for Light Room",
    "GS Spirit Temple Boulder Room",
    "GS Spirit Temple Hall to West Iron Knuckle",
    "GS Spirit Temple Lobby"
];
